### PR TITLE
Add two relays

### PR DESCRIPTION
**Pull request by jkriege2**

### CODE REVIEW

**Comment by jkriege2** [comment]
see these pull requests for schematic symbols:
https://github.com/KiCad/kicad-library/pull/693
https://github.com/KiCad/kicad-library/pull/691

**Comment by jkriege2** [comment]
I added 3d models for all relays and made the pads oval and a bit larger. The 3d models are available from these pull requests:
https://github.com/KiCad/kicad-library/pull/693
https://github.com/KiCad/kicad-library/pull/691

frt5
frt5s
hjr4102
hjr4102s

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: Relay_DPDT_FRT5
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
checking module: Relay_SPDT_HJR-4102
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
```

* Silkscreen is not superposed to pads, its outline is completely visible after board assembly

**Comment by jkriege2** [comment]
better this way?

Best,
JAN

**Comment by pointhi** [comment]
* remove the silk screen from the pads
* The holes of the pads are to small

the rest looks fine

**Comment by jkriege2** [comment]
- silk screen was already moved away from the pads
- drill size is 1mm now, note these are DIP relays with tiny/thin pins ;-)
- I moved CrtYrd onto the appropriate raster 

=> both footprints check out OK now for me.

Best,
JAN

**Comment by pointhi** [comment]
I thought about the Silk layer which can be enabled for pads:
kicad_pad_silkscreen
In old KiCad versions, there was the Silkscreen layer added by default, which doesn't make sense at all.

**Comment by jkriege2** [comment]
aahhh ... I didn't see that ... should be fixed now.

**Comment by pointhi** [comment]
Thanks for your contribution.

It's great to see a new mass contributor. Learning the KLC needs some time at the beginning, but with time, maintainers find less and less things to complain about and then merging goes much smoother.

**Comment by jkriege2** [comment]
some questions/suggestions: 
1. Could one move the removal of SlkScreen on TH-pads to the Python check-script?
2. Would it be possible to extend the KLC-description in the Wiki with examples and screenshots? That would make it much easier to understand them!

Best,
JAN

**Pull request merged**
