### PR TITLE
rename footprint and correct link to 3d model

### PR DESCRIPTION
**Pull request by andres53016**
rename footprint and correct links to 3d models

### CODE REVIEW

**Comment by michal777** [comment]
Relay_SPDT_SingleRow_Laying_FinderType34Point51.kicad_mod is broken. Tere should be ')' under "rotate", in the same column that '(' before "model".
In:
Relay_SPST_Schrack-RP-3SL_mono.kicad_mod
Relay_SPST_Schrack-RP-3SL_bistable.kicad_mod
there is wrong scale - there was 0.3937 to scale metric to imperial. The offset for them should be something about: x=0.476, y=0.1417.
The " " in 3d model paths are unnecessary, kicad doesn't add them if there is no need.

**Comment by michal777** [comment]
Could you also mirror the Relay_SPDT_SingleRow_Standing_FinderType34Point51 in x axis?
It doesn't match 3d model because footprint is mirrored.

**Comment by michal777** [comment]
Thanks for fixing this mirrored relay, please let me know if you will make other fixes (if not, I will finish it). The most important is to fix the lacking ")". With this bug the library can't be opened.

**Comment by andres53016** [comment]
Hi, I do not understand the bug you mention.You could explain to me, so I fix them.

**Comment by michal777** [comment]
Do you read these messages on github or mail client? I described it in other post. Have you read it?

Here is link to changed file: https://github.com/andres53016/Relays_ThroughHole.pretty/blob/master/Relay_SPDT_SingleRow_Laying_FinderType34Point51.kicad_mod
Bracket opened in line 1 is closed in line 57 (should be 58). Bracket opened in line 53 is not closed (sholuld be two spaces and right bracket in line 57).

**Comment by andres53016** [comment]
Sorry, my mistake. I fixed this.

**Comment by michal777** [comment]
Thanks for fixing this. I can merge it but I suppose you didn't get my first message:
>In:
>Relay_SPST_Schrack-RP-3SL_mono.kicad_mod
>Relay_SPST_Schrack-RP-3SL_bistable.kicad_mod
>there is wrong scale - there was 0.3937 to scale metric to imperial. The offset for them should be >something about: x=0.476, y=0.1417.
>The " " in 3d model paths are unnecessary, kicad doesn't add them if there is no need.
Could you fix it?

**Comment by andres53016** [comment]
Fixed, I not read this message, from now I read the messages here.

**Comment by michal777** [comment]
Now it's great. Thanks for contribution.

**Pull request merged**
