### PR TITLE
add footprint for Panasonic JW2 relays

### PR DESCRIPTION
**Pull request by mignon-p**
This is a footprint for [Panasonic JW2 relays](http://www3.panasonic.biz/ac/e_download/control/relay/power/catalog/mech_eng_jw.pdf).  It is meant to go with [this schematic symbol](https://github.com/KiCad/kicad-library/pull/1416).

jw2-footprint

### CODE REVIEW

**Comment by hackscribble** [comment]
Hi @ppelleti 

For this size of component, I would move the courtyard out to 0.5mm clearance (currently it's 0.25mm).  With that change, this will be OK to merge.

Many thanks

**Comment by ppelleti** [comment]
Thanks!  I've increased the courtyard to 0.5.  I generated the footprint with [this script](https://gist.github.com/ppelleti/48d020b3a7dcd5abfa99f9d35666bff5).

jw2-courtyard0 5

**Comment by poeschlr** [comment]
Has there been a policy change about the courtyard clearance i missed? (I was away a few days.)
I thought it is always 0.5mm.
Why would a larger (higher) component need more space for the pic and place machine?

**Comment by hackscribble** [comment]
@poeschlr Maybe I read too much into the KLC wording ...

`Connectors, canned capacitors, crystals, should have a clearance of 0.5mm`

I thought those were examples of larger components, to contrast with the previous KLC point ...

`Components smaller than 0603 should have a clearance of 0.15mm`

**Comment by poeschlr** [comment]
Connectors have a larger clearance to make it easier to connect the mating part.
Crystals because of emc.
I'm not sure about the canned caps. Maybe there is a mention of them in some standard?
The 0.15 for very small parts comes form a standard i think. Maybe @SchrodingersGat could enlighten us.

**Comment by SchrodingersGat** [comment]
0.15mm is the 'least dense' recommendation for IPC-7351, and is the default value unless there are other considerations such as those @poeschlr has enumerated above.

**Comment by hackscribble** [comment]
Thanks @poeschlr and @SchrodingersGat 

@ppelleti Sorry for the mixup.  Please revert the courtyard clearance to 0.25mm and then this will be OK to merge.

**Comment by ppelleti** [comment]
OK, I've removed commit db4aaba603394f5caf5fb6961d294e532bac2e52 from my branch, which is the commit that increased the courtyard to 0.5.  That just leaves commit f5cd18969c6221f1036563be61d0ae5bc26e6c7d, which is the original one with a 0.25 courtyard.

**Comment by hackscribble** [comment]
Many thanks @ppelleti

**Pull request merged**
